backend:
  name: git-gateway
  branch: main

media_folder: 'public/images'
public_folder: '/images'

collections:
  - name: 'site'
    label: 'Site'
    files:
      - file: 'content/site.json'
        label: 'Informations'
        name: 'infos'

        fields:
          - { label: 'Titre accueil', name: 'heroTitle', widget: 'string' }

          - { label: 'Sous titre', name: 'subtitle', widget: 'string' }

          - { label: 'Téléphone', name: 'phone', widget: 'string' }

          - { label: 'Email', name: 'email', widget: 'string' }

          - label: 'Galerie'
            name: 'gallery'
            widget: 'list'
            field: { label: 'Image', name: 'image', widget: 'image' }
